### ISSUE TITLE
建议更新conf.py文件

### ISSUE THREAD

**Issue by UnadXiao** [zh-google-styleguide/zh-google-styleguide#100]
在Sphinx v2.0.0上make会报如下问题：
> Running Sphinx v2.0.0
> loading translations [en_US]... not available for built-in messages
> 
> Extension error:
> Could not import extension sphinx.ext.pngmath (exception: No module named 'sphinx.ext.pngmath')

屏蔽conf.py文件的15行
> extensions = ['sphinx.ext.pngmath'] 

可以解决以上问题.所以建议更新下最新的conf.py文件

**Comment by flydt** [comment]
我这样解决的：
git diff
diff --git a/conf.py b/conf.py
index 648f54b..293f057 100644
--- a/conf.py
+++ b/conf.py
@@ -12,7 +12,8 @@ source_suffix = '.rst'
 master_doc = 'contents'
 language = 'en_US'
 exclude_patterns = ['_build']
-extensions = ['sphinx.ext.pngmath']
+# extensions = ['sphinx.ext.pngmath']
+extensions = ['sphinx.ext.imgmath']
 pygments_style = 'sphinx'
