### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by mapengfei-nwpu** [zh-google-styleguide/zh-google-styleguide#106]
在编译的时候碰到的问题是
exception: No module named 'sphinx.ext.pngmath'

**Comment by flydt** [comment]
pip install Sphinx sphinx_rtd_theme imgmath
apt install latexmk texlive-xetex context texlive-base texlive-extra-utils texlive-lang-cjk texlive-latex-extra texlive-latex-recommended texlive-plain-generic

**Comment by mapengfei-nwpu** [comment]
谢谢啦，其他的都没问题，就是没找到imgmath，换了很多pip源，都没有找到，python3和python2都试过了。

**Comment by dekaiidea** [comment]
It is mentioned in [the sphinx-doc](https://github.com/sphinx-doc/sphinx/issues/6182)  that pngmath module was removed since 1.8(now is 2.1),the successor is `sphinx.ext.imgmath`.
So you need write `sphinx.ext.imgmath` instead of `sphinx.ext.pngmath` in line 15 of conf.py

**Comment by wikinee** [comment]
最新版本已修复。
