### ISSUE TITLE
C++ 9.19. 水平留白中有处注释错误

### ISSUE THREAD

**Issue by AimTao** [zh-google-styleguide/zh-google-styleguide#109]
如图，标记处的应该是  `括号`  ->  `空格`

`用空格把大括号与实现分开.`

![Xnip2020-05-30_13-05-54](https://user-images.githubusercontent.com/46548984/83320126-f5afc800-a276-11ea-907c-2077f885b55c.png)

**Comment by wikinee** [comment]
已修复，欢迎下一次提交 merge request。
