### ISSUE TITLE
变成正式的独立项目吧！

### ISSUE THREAD

**Issue by acgtyrant** [zh-google-styleguide/zh-google-styleguide#11]
刚提交的某 pull request 被 merged 后，发现我的 contributions graph 居然没计入这些 commits! [Commit was made in a fork](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork) 提到：

* To detach the fork and turn it into a standalone repository on GitHub, contact GitHub support.

所以我现在去联系 GitHub support 了，摇身一变成正式的独立项目吧！

**Comment by acgtyrant** [comment]
效率之快令人咋舌，Done.

@yangyubo 你可以删掉你的那个原项目了。

**Comment by yangyubo** [comment]
没搞明白是怎么回事？

**Comment by acgtyrant** [comment]
原本的 zh-google-styleguide/zh-google-styleguide 是 yangyubo/zh-google-styleguide 的 fork, 所以我对前者的 commits 不会计入我的 contribution graphs, 于是我联系 GitHub support 申请让前者变成独立的项目。现在它已经不再是 yangyubo/zh-google-styleguide 的 fork 了。

**Comment by yangyubo** [comment]
原来可以这样，没问题，我找时间修改一下老仓库。
