### ISSUE TITLE
请问你们有相关的C++插件吗？

### ISSUE THREAD

**Issue by WuZhengqiang666** [zh-google-styleguide/zh-google-styleguide#115]
zh-google-styleguide的工作人员你们好：
你们有这样的插件吗？ 
当你的编码**不符合**谷歌要求的编码风格，他会让**编译器弹出警告**，并**要求你修改**。

如图：
![image](https://user-images.githubusercontent.com/49598775/94652052-03ac4d00-032c-11eb-955e-f52e3a9f9ef8.png)
这个是阿里巴巴的Java 规约插件https://github.com/alibaba/p3c

有没有**谷歌C++代码规约**的插件呢？帮助我养成良好C++编码风格。

感谢！

**Comment by wikinee** [comment]
你好，没有。
你在使用 IDEA，这是java的集成开发环境，你提到的插件也是 alibaba 专门编写的。
JetBrains 对 C++ 开发的工具叫clion，你可以搜索想换格式化插件，解决你的问题。
