### ISSUE TITLE
scoped_ptr  已经过时？

### ISSUE THREAD

**Issue by cathaysia** [zh-google-styleguide/zh-google-styleguide#128]
在 [5. 来自 Google 的奇技](https://github.com/zh-google-styleguide/zh-google-styleguide/blob/master/google-cpp-styleguide/magic.rst) 一文的 *译者注* 中，译者认为 *scoped_ptr* 已经过时。但是实际上 scoped_ptr 现在依然是一种行之有效且非常好用的手法，只是不知道为什么标准库没提供而已。

尽管 shared_ptr 看起来是未来，但是事实上 shared_ptr 有很多坑 <sup><a href="https://www.jianshu.com/p/f1925247c14f">1<a/></sup> ，而且在多线程中表现不佳，所以我认为译者注的第三条应当去掉

[注1] [C++ shared_ptr四宗罪(不得不转)](https://www.jianshu.com/p/f1925247c14f)

**Comment by wikinee** [comment]
个人精力有限，没法紧跟上游翻译，欢迎提交 pr。
