### ISSUE TITLE
大量 Title underline too short 告警

### ISSUE THREAD

**Issue by yangyubo** [zh-google-styleguide/zh-google-styleguide#13]
大部分文本编辑器 (包括 OS X) 为了优化汉字显示, 实际上汉字占宽是英文的 1.5 倍, 但是实际上 sphinx, reStructuredText 和 Terminal 等, 都内部将汉字解析成 2 倍英文字符宽度.

所以文本编辑器显示的时候是 header 和下划线是左右对齐的, 但是实际上内部解析是不对齐的.

我通常的解决方法是下划线对齐后, 再增长至 2 倍或 1.5 倍.

```
7. 注释
------
/home/docs/checkouts/readthedocs.org/user_builds/zh-google-styleguide/checkouts/latest/google-cpp-styleguide/comments.rst:9: WARNING: Title underline too short.
```

**Comment by acgtyrant** [comment]
好，我写个脚本批量处理文件，增长下下划线为两倍。

**Comment by acgtyrant** [comment]
我发现就算下划线增加为两倍，Gvim 下某标题依旧比下划线还长，增加为三倍没问题吗？

**Comment by yangyubo** [comment]
应该没问题，只要不短于标题。

**Comment by acgtyrant** [comment]
谢谢 @brickgao 的帮忙。
