### ISSUE TITLE
readme 中 JavaScript 文档的链接报 404

### ISSUE THREAD

**Issue by WqVoon** [zh-google-styleguide/zh-google-styleguide#138]
应该是因为当前 js 目录中没有 index.rst 文件，感觉可以像 ts 的做法，在链接后面加入 /contents 的 path

感谢各位的精彩翻译，辛苦 :-)

**Comment by iyongliang** [comment]
https://github.com/zh-google-styleguide/zh-google-styleguide/releases/tag/v0.6
