### ISSUE TITLE
本项目只是机翻(机器翻译)加少量人工校正?

### ISSUE THREAD

**Issue by sisrfeng** [zh-google-styleguide/zh-google-styleguide#153]
阅读翻译后的文档时, 老是感觉从中文里读出了英文原文...
如果只是翻译, 没有结合中国人编程的习惯进行修改, 那我觉得英语好的, 可以直接看英文原版了

**Comment by iyongliang** [comment]
这个项目早期肯定是人工翻译的，不过目前那些人都不维护了。
我觉得这个项目存在的目的是方便国内程序员意识到有这件事，看不看英文原版那是他们的选择了。
