### ISSUE TITLE
正式发布 Google CPP Style Guide 4.45 的翻译

### ISSUE THREAD

**Issue by acgtyrant** [zh-google-styleguide/zh-google-styleguide#16]
麻烦 @yangyubo 重新编译下网站吧。

**Comment by yangyubo** [comment]
@acgtyrant @lilinsanity 两位辛苦了, C++ 风格指南时隔很久没有和英文版同步, 这次更新可谓是焕然一新, 值得庆祝!

@acgtyrant 我给项目设置了钩子 (hook), 一旦有提交便会自动通知 readthedocs 重新生成 HTML 页面. 我刚刚去看了一下, 已经是最新的 4.45 版本了.

Cheers!
