### ISSUE TITLE
离线的其他格式在哪里啊

### ISSUE THREAD

**Issue by wikinee** [zh-google-styleguide/zh-google-styleguide#25]
> 中文版项目采用 reStructuredText 纯文本标记语法, 并使用 Sphinx 生成 HTML / CHM / PDF 等文档格式.

我没有找到啊，请问PDF文档在哪啊
另：谢谢翻译，看英文好吃力

**Comment by xuxinkun** [comment]
可以把整个项目clone下来，然后使用sphinx-build，即可以生成对应格式。

**Comment by lilinsanity** [comment]
是这样的，在侧边栏有一个 v:latest 链接，点击后可以看到 PDF Epub 等版本的下载链接。
