### ISSUE TITLE
reStructuredText格式转换为markdown格式过程中的问题及解决方法

### ISSUE THREAD

**Issue by ilcc** [zh-google-styleguide/zh-google-styleguide#32]
# reStructuredText格式转换为markdown格式过程中的问题及解决方法
## Q: 为什么要把reStructuredText格式转换为markdown格式？
1. 在当前版本中大量存在中英文标点混用的情况（逼死强迫症:D），既然本项目致力于将英文版翻译为中文版，强烈建议使用统一的中文标点，而使用统一的中文标点会造成Sphinx解析格式错误，参见https://github.com/zh-google-styleguide/zh-google-styleguide/pull/30 。对于markdown格式目前没有这类解析格式错误。
2. markdown格式相对reStructuredText格式使用的人更多，入门门槛较低，也便于中文版本格式维护。
## Q: 你计划转换本仓库的哪些部分？

基于个人兴趣和时间因素考虑，我仅计划转换《Google C++风格指南》这一部分，其他部分暂无计划，希望有同样兴趣的GitHuber能接力完成剩下部分的格式转换。
## Q: 你将如何实现reStructuredText格式到markdown格式的转换？

基于对各种自动化、半自动化转换工具的不信任，我将采用纯手工这一最原始的方式进行转换，如果你有任何理想的转换工具推荐，请@我进行推荐。
## Q: 转换工作包括哪几步？
1. 在不改变文本内容的前提下，将rst格式转换为md格式。
2. 统一文件中的标点为中文标点。
3. 修正个别翻译不通顺的语句。
## Q: 提这个Issue的原因是什么？

在转换的过程中必然会遇到一些问题，也会针对这些问题寻求大家的帮助，以便找到解决问题的方法。我计划把转换过程中遇到的问题都记录在此Issue中，在转换工作完成后，如果时间允许，计划将此Issue中的问题与解决方法进行整理，方便以后有其他人计划将reStructuredText格式转换为markdown格式时能从此Issue中获得灵感。
## Q: 怎么查看正在进行中的转换工作？

所有的转换工作都在[ilcc/zh-google-styleguide](https://github.com/ilcc/zh-google-styleguide)仓库的`feature-markdown`分支中进行。
## Q: 怎么联系你？

如果你对转换工作有任何的建议和意见，请在**此Issue**中留言，并@ilcc方便我及时了解你的想法和建议。

**Comment by ilcc** [comment]
问题：在reStructuredText格式中支持

    :ref:`define-guard`

对文件内段落进行引用（在`google-cpp-styleguide/headers.rst`文件的第19行），markdown不支持此种引用。
解决方法：暂时没有。

**Comment by yangyubo** [comment]
👍
@ilcc 用纯 markdown 功能很有限, 目录什么的都没法自动生成/更新, 建议先选定一个带扩展的 markdown 的静态页面生成器, 并支持方便的集成到 GitHub Pages

**Comment by lilinsanity** [comment]
1. 经过订正，中英文标点混排的问题在已订正的部分中已经解决。
2. 如上 @yangyubo 所说，Markdown 的功能有限，且无法实现最基本的内部引用功能。
3. 此 issue 已发布一年，发布者主题中所引用的仓库已经被删除，且在发布者的资料中没有相关的仓库。

基于以上三个原因，我认为这一 issue 已没有作用，可以关闭。
