### ISSUE TITLE
java style有吗？

### ISSUE THREAD

**Issue by willxuecn** [zh-google-styleguide/zh-google-styleguide#39]
你好，java style有在进行吗？

**Comment by yangyubo** [comment]
没有

**Comment by gujunhk** [comment]
留给Ali，让他们抄呢。。。最近他们刚出的，前半部高仿。

**Comment by Ynjxsjmh** [comment]
[Google Java Style Guide](https://google.github.io/styleguide/javaguide.html) 这个和这个 repo 有关么？
