### ISSUE TITLE
大量的<code>#include</code>s被写成<code>#includes</code>

### ISSUE THREAD

**Issue by MrJasper** [zh-google-styleguide/zh-google-styleguide#40]
如题，请查看<http://google.github.io/styleguide/cppguide.html#Self_contained_Headers>这里的源代码和ReadTheDocs中的对应文本。

**Comment by yangyubo** [comment]
@MrJasper 谢谢指正，能否提交一个 pull request？

**Comment by MrJasper** [comment]
当然可以。另外我觉得加s表示复数是英文的语法，中文的话应该直接写#include吧？

**Comment by MrJasper** [comment]
已经提交并更新内容，见 #43 。经验不足有错误的地方还请指出。

**Comment by yangyubo** [comment]
@MrJasper 非常感谢你的帮助！在线文档应该已经自动更新了（设置了 Push Hook 触发器）。
