### ISSUE TITLE
Any updates of this project?

### ISSUE THREAD

**Issue by 4wheels** [zh-google-styleguide/zh-google-styleguide#8]
This long time before this repo was updated. Is there any problem of translating? Or is this project no longer needed because others may have create a better one?

Please let me know the latest news of this project. Thank you.

**Comment by cheerslee** [comment]
Sorry?I think you have writed to the wrong person.

**Comment by 4wheels** [comment]
@cheerslee I wrote the issue to members of this project. Sorry to interrupt you, but I will wait until another member to reply.

**Comment by yangyubo** [comment]
@4wheels contributions are welcome

**Comment by 4wheels** [comment]
Alright, thanks both of you. @cheerslee @yangyubo
